version: '3.9'

services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "443:443"
    depends_on:
      - trading_analyze_api

  trading_analyze_api:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: ../
    env_file:
      - ../.env/.dev.env
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../alembic/versions:/app/alembic/versions
      - ../logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.dev.env
    volumes:
      - /var/lib/trading_analyze_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"