version: '3.9'

services:
  proxy:
    depends_on:
      - trading_analyze_api
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "443:443"

  trading_analyze_api:
    env_file:
      - ../.env/.env
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    volumes:
      - /var/log/trading_analyze_api:/app/logs
    depends_on:
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/trading_analyze_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
