version: '3.9'

services:
  metro_alarm_service_auth:
    env_file:
      - ../.env/.env
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../alembic/versions:/app/alembic/versions
      - ../logs:/app/logs
    depends_on:
      postgres_auth:
        condition: service_healthy
    networks:
      - msa

  postgres_auth:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/metro_alarm_server_auth_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - msa

networks:
  msa:
    driver: bridge
    external: true