version: '3.9'

services:
  proxy:
    depends_on:
      - trading_analyze_api
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "443:443"

  trading_analyze_api:
    env_file:
      - ../.env/.env
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../alembic/versions:/app/alembic/versions
      - ../logs:/app/logs
    ports:
      - "8081:8081"
    depends_on:
      postgres:
          condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/metro_alarm_server_auth_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5431:5431"
